services:
  - type: web
    plan: free
    name: header-parser
    runtime: node
    repo: https://github.com/michellemtchai/header-parser.git
    buildCommand: 'yarn install'
    startCommand: 'yarn start'
